apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-ca.fullname" . }}--msp-tls-cryptomaterial
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  keyfile: {{ .Values.msp.tlsCAKeyFile | b64enc | quote }}
  certfile:  {{ .Values.msp.tlsCACertFile | b64enc | quote }}
  chainfile:  {{ .Values.msp.tlsCAChainfile | b64enc | quote }}
