apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-ca.fullname" . }}--tls-cryptomaterial
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  tls.key: {{ .Values.msp.tlsKeyFile | b64enc | quote }}
  tls.crt: {{ .Values.msp.tlsCertFile | b64enc | quote }}
