apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-orderer.fullname" . }}--ord
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  ## Location where fabric-ca-client configuration is saved
  FABRIC_CA_CLIENT_HOME: /var/hyperledger/fabric-ca-client
  ## Orderer defaults
  ORDERER_CFG_PATH: /var/hyperledger/config
  ORDERER_GENERAL_LEDGERTYPE: file
  ORDERER_FILELEDGER_LOCATION: /var/hyperledger/ledger
  ORDERER_GENERAL_BATCHTIMEOUT: 1s
  ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT: "10"
  ORDERER_GENERAL_MAXWINDOWSIZE: "1000"
  ORDERER_GENERAL_ORDERERTYPE: {{ .Values.ord.type | quote }}
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
  ORDERER_GENERAL_LISTENPORT: "7050"
  ORDERER_GENERAL_LOGLEVEL: {{.Values.logging.spec}}
  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/msp
  ORDERER_GENERAL_LOCALMSPID: {{ .Values.ord.mspID | quote }}
  ORDERER_GENERAL_BOOTSTRAPMETHOD: {{.Values.bootstrapMethod}}
  ORDERER_GENERAL_GENESISFILE: /hl_config/genesis/genesis.block
  ORDERER_GENERAL_GENESISPROFILE: initial
  ORDERER_GENERAL_TLS_ENABLED: {{ .Values.ord.tls.server.enabled | quote }}
  ORDERER_GENERAL_TLS_CERTIFICATE: "/var/hyperledger/tls/server/pair/tls.crt"
  ORDERER_GENERAL_TLS_PRIVATEKEY: "/var/hyperledger/tls/server/pair/tls.key"
  ORDERER_GENERAL_TLS_ROOTCAS: "/var/hyperledger/tls/server/cert/cacert.pem"
  ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED: {{ .Values.ord.tls.client.enabled | quote }}
  # see: https://lists.hyperledger.org/g/fabric/topic/31696729
  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE: "/var/hyperledger/tls/server/pair/tls.crt"
  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY: "/var/hyperledger/tls/server/pair/tls.key"
  ORDERER_GENERAL_CLUSTER_ROOTCAS: "/var/hyperledger/tls/server/cert/cacert.pem"
  # This is fixed prior to starting the orderer
  ORDERER_GENERAL_TLS_CLIENTROOTCAS: "/var/hyperledger/tls/client/cert/*"

  # Admin API
{{- if .Values.channelParticipationEnabled }}

  ORDERER_CHANNELPARTICIPATION_ENABLED: "{{.Values.channelParticipationEnabled}}"
  ORDERER_ADMIN_TLS_ENABLED: "true"
  ORDERER_ADMIN_TLS_CERTIFICATE: "/var/hyperledger/admin/tls.crt"
  ORDERER_ADMIN_TLS_PRIVATEKEY: "/var/hyperledger/admin/tls.key"
  ORDERER_ADMIN_TLS_ROOTCAS: "[/var/hyperledger/admin/cacert.crt]"
  ORDERER_ADMIN_TLS_CLIENTROOTCAS: "[/var/hyperledger/admin/clientcacert.crt]"
  ORDERER_ADMIN_LISTENADDRESS: "0.0.0.0:7053"

{{- end }}

  GODEBUG: "netdns=go"
  ADMIN_MSP_PATH: /var/hyperledger/admin_msp
  FABRIC_LOGGING_SPEC: {{.Values.logging.spec}}
  ##############
  # Metrics #
  ##############
  ORDERER_METRICS_PROVIDER: "prometheus"
  ##############
  # Operations #
  ##############
  ORDERER_OPERATIONS_TLS_ENABLED: "false"
  ORDERER_OPERATIONS_LISTENADDRESS: "0.0.0.0:9444"
