{{- if .Values.istio.hosts -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "hlf-orderer.fullname" . }}-gateway
spec:
  selector:
    istio: {{.Values.istio.ingressGateway}}
  servers:
    - port:
        number: {{.Values.istio.port}}
        name: tcp
        protocol: TLS
      tls:
        mode: PASSTHROUGH
      hosts:
          {{- range .Values.istio.hosts }}
          - {{ . }}
          {{- end }}

{{- end -}}
