apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-orderer.fullname" . }}-cacert
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  cacert.pem: {{ .Values.cacert | b64enc | quote }}
