apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-orderer.fullname" . }}-idcert
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  cert.pem: {{ .Values.cert | b64enc | quote }}

