{{- if .Values.channelParticipationEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-orderer.fullname" . }}-admin
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.admin.cert | b64enc | quote }}
  tls.key: {{ .Values.admin.key  | b64enc | quote }}
  cacert.crt: {{ .Values.admin.rootCAs  | b64enc | quote }}
  clientcacert.crt: {{ .Values.admin.clientRootCAs  | b64enc | quote }}
{{- end }}
