apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-orderer.fullname" . }}--genesis
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  # genesis is already base64
  genesis.block: {{ .Values.genesis | quote }}
