apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-orderer.fullname" . }}-peer-tlsrootcert
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
{{- range $kk, $vv := .Values.clientcerts }}
  {{ $kk }}: {{ $vv | b64enc|quote }}
{{- end }}