# permissions for end users to edit fabricchaincodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricchaincode-editor-role
rules:
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricchaincodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricchaincodes/status
  verbs:
  - get
