# permissions for end users to view fabricpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricpeer-viewer-role
rules:
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricpeers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricpeers/status
  verbs:
  - get
