# permissions for end users to view fabricorderernodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricorderernode-viewer-role
rules:
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricorderernodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricorderernodes/status
  verbs:
  - get
