# permissions for end users to edit fabriccas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricca-editor-role
rules:
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabriccas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabriccas/status
  verbs:
  - get
