# permissions for end users to view fabricorderingservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricorderingservice-viewer-role
rules:
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricorderingservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricorderingservices/status
  verbs:
  - get
