# permissions for end users to view fabricchaincodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricchaincode-viewer-role
rules:
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricchaincodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricchaincodes/status
  verbs:
  - get
