# permissions for end users to edit fabricorderernodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricorderernode-editor-role
rules:
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricorderernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.zhangfuli.com
  resources:
  - fabricorderernodes/status
  verbs:
  - get
