apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-peer.fullname" . }}-tlsrootcert
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  cacert.pem: {{ .Values.tlsrootcert | b64enc | quote }}
