{{- if .Values.intCACert}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-peer.fullname" . }}-intcacert
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  intcacert.pem: {{ .Values.intCACert | b64enc | quote }}

{{- end }}