{{- if .Values.intTLSCACert}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-peer.fullname" . }}-tlsintcacert
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  intcacert.pem: {{ .Values.intTLSCACert | b64enc | quote }}

{{- end }}