apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-peer.fullname" . }}--tlsclientrootcerts
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  cert.pem: {{ .Values.tlsrootcert | b64enc | quote }}
