apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-peer.fullname" . }}-tls-ops
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.opsTLS.cert | b64enc | quote }}
  tls.key: {{ .Values.opsTLS.key  | b64enc | quote }}