apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}-fs
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "hlf-peer.name" . }}
    release: {{ .Release.Name }}
