{{- if .Values.istio.hosts -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "hlf-peer.fullname" . }}-virtualservice
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - {{ include "hlf-peer.fullname" . }}-gateway
  tls:
    - match:
        - port: 443
          sniHosts:
          {{- range .Values.istio.hosts }}
              - {{ . }}
          {{- end }}
      route:
        - destination:
            host: {{ include "hlf-peer.fullname" . }}
            port:
              number: 7051
{{- end -}}
